### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/blindfolded_traveler_2D#1]
- [x] Add CHS belief (How to handle 2D robot width when creating CHS?)
- [ ] Add IG strategy
- [ ] Add MCTS strategy
- [ ] Make more scenarios that show off pros and cons of various strategies
- [ ] Further example single wall scenario where prior obstacle does not match true obstacle
- [x] Examine multi-obstacle scenario where prior does not match true
- [x] Change multi-object scenario to have manually set prior rectangles, and noise around that
- [x] Plotter for displaying results of trials
- [x] Projections for obstacles states onto observations
